// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjldvjzdlvgslcbhzwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuamxkdmp6ZGx2Z3NsY2JoendwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1ODI0ODEsImV4cCI6MjA4MzE1ODQ4MX0.1vXDOAst6XDhYF1fEOpaTOqjtpzdr8Y9J9QsmzNV01k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});